### ISSUE TITLE
what is ment by "global"

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssbc.github.io#2]
in several places on the doc site the word "global" is used.
This seems misleading to me.
"global" suggests that everything is replicated to everything.
A global variable is a variable that every part of a program can see.
A global issue is an issue that affects everyone on earth.
A global phenomena is one that is happening everywhere on earth, or at least, in many places but spread pretty evenly.

hopefully one day ssb will be a global phenomena, although since we have users in at least 4 continents you could claim it already is?

But, it would be wrong to say that your node replicates globally - since it only replicates with peers in or connected to your social network - that may or may not be global?

It seems more useful to say that it's a "social" gossip protocol? or is there another word that might work?

@clehner @mixmix @pfraze ?

**Comment by pfrazee** [comment]
I did a quick grep of its usages, and there's two notable times it's used:
- "Secure Scuttlebutt: a global database protocol" (in the nav)
- "**Secure-Scuttlebutt (SSB)** - A protocol for replicating logs in a global gossip network."

Whenever I've read/written "global", I've thought of it as distinguishing from databases which don't interface with the outside world, which is most DBs. Gossip networks are usually inside a trust-region (eg somebody's data center), so my thinking is a _global_ gossip network spans trust-regions

But there's the usage of "global" to mean "singleton," which I agree is a more common meaning, and so a source of confusion here.

Social is an interesting choice. 
- "Secure Scuttlebutt: a social database protocol"
- "**Secure-Scuttlebutt (SSB)** - A protocol for replicating logs in a social gossip network."

No other words come to mind, yet

**Comment by dominictarr** [comment]
oh, now I see where you are coming from. "social" does have a few weird implications because I suspect that people with first think of "socializing", and how are they gonna socialize with a database?

what about "replicated" database protocol, or "replication-first" database protocol?

**Comment by pfrazee** [comment]
replicated may work but it doesnt have a lot of oomph. Going to mull this over instead of tossing out a bunch of weak suggestions (like I normally do)

**Comment by pfrazee** [comment]
Perhaps "mesh". "Secure Scuttlebutt: a database mesh protocol."

**Comment by dominictarr** [comment]
"replication" is also quite a technical term. 
kinda want to say "neibourhood"?

maybe ask what properties we want to communicate?

**Comment by pfrazee** [comment]
Oh, what about p2p?

**Comment by dominictarr** [comment]
p2p is a little bit of a weird term also. For example, a dht or a block
chain is also a p2p database, but these all have very different properties.

I think we need to communicate that the database can be shared across trust
boundaries, and that you can do an offline write.

Hmm, maybe we should leave this for now, and instead focus on a description
of what makes ssb unique

**Comment by clehner** [comment]
My 2¢:
- Replace "Global replication" with "Friend of a friend replication"
- Replace "Scuttlebot's global database protocol" with "Scuttlebot's database protocol"
- Replace "global gossip-protocol mesh" with "gossip-protocol mesh". Or leave it as is

**Comment by pfrazee** [comment]
@clehner or maybe "friend to friend" replication

**Comment by mixmix** [comment]
This seems like it could be discussed in patchwork.

Sounds like there is a question of who this jargon is for. I.e. General
users or technical devs

**Comment by pfrazee** [comment]
fwiw the site describes scuttlebot as a "p2p log store" right now

**Comment by mixmix** [comment]
Replicating distributed database.
Self healing distributed database

User hosted Just-your-friends database

Mesh neighborhood database

**Comment by pfrazee** [comment]
I think there's something pretty appealing (and accurate) to [friend-to-friend](https://en.wikipedia.org/wiki/Friend-to-friend)

**Comment by pfrazee** [comment]
another way we could go at things is to highlight that it's all user-device focused

**Comment by pfrazee** [comment]
I was reading https://en.wikipedia.org/wiki/Gossip_protocol and noticed the description there is quite good

> A gossip protocol is a style of computer-to-computer communication protocol inspired by the form of gossip seen in social networks

"global gossip protocol" might be good for ssb

**Comment by dominictarr** [comment]
hey, (channeling @dust here) what about "galactic"?
- it's vauger than global, so doesn't carry those specific connotations that dislike
- still suggests that anyone can access it
- galactic sounds bigger than "inter-planetary" so ipfs can eat it ;)

**Comment by dominictarr** [comment]
galactic gossip protocol

**Comment by dominictarr** [comment]
also, the galaxy is very very big, and we don't really know what is going on in most of it, and that is one of the things I want to emphasize about ssb

**Comment by mixmix** [comment]
ooooo galactic gossip protocol

**Comment by pfrazee** [comment]
That does have a nice ring to it, but it sounds sort of like an alternative name to SSB (GGP)

**Comment by dominictarr** [comment]
SSB is a GGP

**Comment by dominictarr** [comment]
if people are warm to galactic lets use it before we start another names debate

**Comment by mixmix** [comment]
Agree. I like it. Hope it doesn't sound petty. I think it's more accessible
than scuttlebutt.

Galactic gossip (for pirates)

**Comment by pfrazee** [comment]
Wait, are we talking about renaming ssb to ggp?

**Comment by pfrazee** [comment]
(Except for the task of renaming repos and what not, I'd actually be in favor of that. I think Galactic Gossip Protocol is a much cooler name.)

**Comment by dominictarr** [comment]
we are _not_ renaming secure scuttlebutt. we are just deciding what to say it is. this is just using the word "global" vs "galactic" to describe the gossip protocol. galactic is what it is, not what it's called. like you are a human, but your name is mix.

**Comment by clehner** [comment]
I like galactic, but what does it mean here? is the system organized like a galaxy, with a radiant center and spiraling outward? or is the network made up of independent galaxies of nodes? or is the protocol intended to be usable anywhere in our galaxy? as a reference to the theory of change it might be a bit oblique

**Comment by dominictarr** [comment]
@clehner see https://github.com/ssbc/ssbc.github.io/issues/2#issuecomment-186958862

it just avoids some of the misleading senses of "global" but means basically very broad and anyone can partake, not limited, etc.

@pfraze intended "global" to mean [outward facing](https://github.com/ssbc/ssbc.github.io/issues/2#issuecomment-179903108) but to me it sounded [evenly or uniformly shared with everyone](https://github.com/ssbc/ssbc.github.io/issues/2#issue-131268999)

**Comment by pfrazee** [comment]
What about "Universal" instead of "Galactic"? 

I'm feeling ok about galactic, but it's a made-up usage in a place where I think we ought to use specific language ("isa"). Universal has prior meaning, but it doesnt ring as nicely (Universal Gossip Protocol)

**Comment by dominictarr** [comment]
I'm not really sure what a "universal gossip protocol" would be. is it a gossip protocol that works with every other gossip protocol? how would you define "universal" in this context?

**Comment by pfrazee** [comment]
Eh, now that I'm reading it back, I don't like it either. Scratch it.

**Comment by pfrazee** [comment]
Ok, why fight it. Let's go with galactic.
